version: "3.8"
services:
  smpl_julia:
    tty: true
    build:
      context: .
      args:
        UserID: ${UserID}
        GroupID: ${GroupID}
    container_name: smpl_julia
    user: ${UserID}:${GroupID}
    environment:
      - DISPLAY
    volumes:
      - $HOME:$HOME
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    ipc: host
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]